/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany._calculadora;

/**
 *
 * @author melhe
 */
public class Calculadora extends javax.swing.JFrame {

    int num1, num2;
    String signo;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelResul = new javax.swing.JLabel();
        jBton7 = new javax.swing.JButton();
        jBtonClear = new javax.swing.JButton();
        jBtonDiv = new javax.swing.JButton();
        jBton8 = new javax.swing.JButton();
        jBton5 = new javax.swing.JButton();
        jBton1 = new javax.swing.JButton();
        jBton4 = new javax.swing.JButton();
        jBton2 = new javax.swing.JButton();
        jBton9 = new javax.swing.JButton();
        jBtonSum = new javax.swing.JButton();
        jBton3 = new javax.swing.JButton();
        jBton6 = new javax.swing.JButton();
        jBtonMulti = new javax.swing.JButton();
        jBton0 = new javax.swing.JButton();
        jBtonResta = new javax.swing.JButton();
        jBtonIgual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(2, 128, 144));
        jPanel1.setForeground(new java.awt.Color(255, 194, 180));

        jLabelResul.setBackground(new java.awt.Color(2, 128, 144));
        jLabelResul.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabelResul.setForeground(new java.awt.Color(251, 143, 103));
        jLabelResul.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelResul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 223, 255)));
        jLabelResul.setOpaque(true);

        jBton7.setBackground(new java.awt.Color(227, 223, 255));
        jBton7.setForeground(new java.awt.Color(198, 65, 145));
        jBton7.setText("7");
        jBton7.setBorderPainted(false);
        jBton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton7ActionPerformed(evt);
            }
        });

        jBtonClear.setBackground(new java.awt.Color(227, 223, 255));
        jBtonClear.setForeground(new java.awt.Color(198, 65, 145));
        jBtonClear.setText("C");
        jBtonClear.setBorderPainted(false);
        jBtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonClearActionPerformed(evt);
            }
        });

        jBtonDiv.setBackground(new java.awt.Color(227, 223, 255));
        jBtonDiv.setForeground(new java.awt.Color(198, 65, 145));
        jBtonDiv.setText("/");
        jBtonDiv.setBorderPainted(false);
        jBtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonDivActionPerformed(evt);
            }
        });

        jBton8.setBackground(new java.awt.Color(227, 223, 255));
        jBton8.setForeground(new java.awt.Color(198, 65, 145));
        jBton8.setText("8");
        jBton8.setBorderPainted(false);
        jBton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton8ActionPerformed(evt);
            }
        });

        jBton5.setBackground(new java.awt.Color(227, 223, 255));
        jBton5.setForeground(new java.awt.Color(198, 65, 145));
        jBton5.setText("5");
        jBton5.setBorderPainted(false);
        jBton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton5ActionPerformed(evt);
            }
        });

        jBton1.setBackground(new java.awt.Color(227, 223, 255));
        jBton1.setForeground(new java.awt.Color(198, 65, 145));
        jBton1.setText("1");
        jBton1.setBorderPainted(false);
        jBton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton1ActionPerformed(evt);
            }
        });

        jBton4.setBackground(new java.awt.Color(227, 223, 255));
        jBton4.setForeground(new java.awt.Color(198, 65, 145));
        jBton4.setText("4");
        jBton4.setBorderPainted(false);
        jBton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton4ActionPerformed(evt);
            }
        });

        jBton2.setBackground(new java.awt.Color(227, 223, 255));
        jBton2.setForeground(new java.awt.Color(198, 65, 145));
        jBton2.setText("2");
        jBton2.setBorderPainted(false);
        jBton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton2ActionPerformed(evt);
            }
        });

        jBton9.setBackground(new java.awt.Color(227, 223, 255));
        jBton9.setForeground(new java.awt.Color(198, 65, 145));
        jBton9.setText("9");
        jBton9.setBorderPainted(false);
        jBton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton9ActionPerformed(evt);
            }
        });

        jBtonSum.setBackground(new java.awt.Color(227, 223, 255));
        jBtonSum.setForeground(new java.awt.Color(198, 65, 145));
        jBtonSum.setText("+");
        jBtonSum.setBorderPainted(false);
        jBtonSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonSumActionPerformed(evt);
            }
        });

        jBton3.setBackground(new java.awt.Color(227, 223, 255));
        jBton3.setForeground(new java.awt.Color(198, 65, 145));
        jBton3.setText("3");
        jBton3.setBorderPainted(false);
        jBton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton3ActionPerformed(evt);
            }
        });

        jBton6.setBackground(new java.awt.Color(227, 223, 255));
        jBton6.setForeground(new java.awt.Color(198, 65, 145));
        jBton6.setText("6");
        jBton6.setBorderPainted(false);
        jBton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton6ActionPerformed(evt);
            }
        });

        jBtonMulti.setBackground(new java.awt.Color(227, 223, 255));
        jBtonMulti.setForeground(new java.awt.Color(198, 65, 145));
        jBtonMulti.setText("X");
        jBtonMulti.setBorderPainted(false);
        jBtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonMultiActionPerformed(evt);
            }
        });

        jBton0.setBackground(new java.awt.Color(227, 223, 255));
        jBton0.setForeground(new java.awt.Color(198, 65, 145));
        jBton0.setText("0");
        jBton0.setBorderPainted(false);
        jBton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBton0ActionPerformed(evt);
            }
        });

        jBtonResta.setBackground(new java.awt.Color(227, 223, 255));
        jBtonResta.setForeground(new java.awt.Color(198, 65, 145));
        jBtonResta.setText("-");
        jBtonResta.setBorderPainted(false);
        jBtonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonRestaActionPerformed(evt);
            }
        });

        jBtonIgual.setBackground(new java.awt.Color(227, 223, 255));
        jBtonIgual.setForeground(new java.awt.Color(198, 65, 145));
        jBtonIgual.setText("=");
        jBtonIgual.setBorderPainted(false);
        jBtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtonIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelResul, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBtonSum, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBton0, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBtonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelResul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtonMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jBtonSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBton0, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton7ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+7);
    }//GEN-LAST:event_jBton7ActionPerformed

    private void jBtonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonSumActionPerformed
        // TODO add your handling code here:
         num1 = Integer.parseInt(jLabelResul.getText());
        signo = "+";
        jLabelResul.setText("");
    }//GEN-LAST:event_jBtonSumActionPerformed

    private void jBtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonMultiActionPerformed
        // TODO add your handling code here:
         num1 = Integer.parseInt(jLabelResul.getText());
        signo = "*";
        jLabelResul.setText("");
    }//GEN-LAST:event_jBtonMultiActionPerformed

    private void jBton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton0ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+0);
    }//GEN-LAST:event_jBton0ActionPerformed

    private void jBtonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonRestaActionPerformed
        // TODO add your handling code here:
         num1 = Integer.parseInt(jLabelResul.getText());
        signo = "-";
        jLabelResul.setText("");
    }//GEN-LAST:event_jBtonRestaActionPerformed

    private void jBtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonIgualActionPerformed
        // TODO add your handling code here:
        num2 = Integer.parseInt(jLabelResul.getText());
        
        switch(signo){
            case "+":
                jLabelResul.setText(Integer.toString(num1+num2));
                break;
            case "-":
            jLabelResul.setText(Integer.toString(num1-num2));
                break;
            case "*":
            jLabelResul.setText(Integer.toString(num1*num2));
                break;
            case "/":
            jLabelResul.setText(Integer.toString(num1/num2));
                break;
        }
    }//GEN-LAST:event_jBtonIgualActionPerformed

    private void jBtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonClearActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText("");
    }//GEN-LAST:event_jBtonClearActionPerformed

    private void jBton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton1ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+1);
    }//GEN-LAST:event_jBton1ActionPerformed

    private void jBton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton2ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+2);
    }//GEN-LAST:event_jBton2ActionPerformed

    private void jBton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton3ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+3);
    }//GEN-LAST:event_jBton3ActionPerformed

    private void jBton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton4ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+4);
    }//GEN-LAST:event_jBton4ActionPerformed

    private void jBton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton5ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+5);
    }//GEN-LAST:event_jBton5ActionPerformed

    private void jBton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton6ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+6);
    }//GEN-LAST:event_jBton6ActionPerformed

    private void jBton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton8ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+8);
    }//GEN-LAST:event_jBton8ActionPerformed

    private void jBton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBton9ActionPerformed
        // TODO add your handling code here:
        jLabelResul.setText(jLabelResul.getText()+9);
    }//GEN-LAST:event_jBton9ActionPerformed

    private void jBtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtonDivActionPerformed
        // TODO add your handling code here:
        num1 = Integer.parseInt(jLabelResul.getText());
        signo = "/";
        jLabelResul.setText("");
    }//GEN-LAST:event_jBtonDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBton0;
    private javax.swing.JButton jBton1;
    private javax.swing.JButton jBton2;
    private javax.swing.JButton jBton3;
    private javax.swing.JButton jBton4;
    private javax.swing.JButton jBton5;
    private javax.swing.JButton jBton6;
    private javax.swing.JButton jBton7;
    private javax.swing.JButton jBton8;
    private javax.swing.JButton jBton9;
    private javax.swing.JButton jBtonClear;
    private javax.swing.JButton jBtonDiv;
    private javax.swing.JButton jBtonIgual;
    private javax.swing.JButton jBtonMulti;
    private javax.swing.JButton jBtonResta;
    private javax.swing.JButton jBtonSum;
    private javax.swing.JLabel jLabelResul;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
